### ISSUE TITLE
cannot be compiled in cmake 3.22.0

### ISSUE THREAD

**Issue by xintaoding** [ivashmak/vsac#3]
the error is shown as follows when Generate:
LAPACK not found.
Eigen found.
OpenCV ARCH: x64
OpenCV RUNTIME: vc14
OpenCV STATIC: OFF
Found OpenCV 3.4.16 in D:/opencv/buildx64/install/x64/vc14/lib
You might need to add D:\opencv\buildx64\install\x64\vc14\bin to your PATH to be able to run your applications.
Configuring done
CMake Error at CMakeLists.txt:62 (add_library):
  No SOURCES given to target: lvsac

CMake Error at CMakeLists.txt:65 (add_library):
  No SOURCES given to target: samples

**Comment by ivashmak** [comment]
The problem seems to be in finding source files from lines [58](https://github.com/ivashmak/vsac/blob/master/CMakeLists.txt#L58)-[59](https://github.com/ivashmak/vsac/blob/master/CMakeLists.txt#L59), because the error message says no sources are given. Could you please check variables SRCS_VSAC and SRCS_SAMPLES, e.g., put message("${SRCS_VSAC}") in CMakelists.txt after line 59. The correct output should be a list of files, in your case it may be empty.

**Comment by xintaoding** [comment]
Yes, I have repaired the problem based on your comments. I had incorrectly uncommented the statements from line 58-59 since I misunderstand the comment "#add_subdirectory(lib/pybind11)" in CMakelists.txt. I have not install python in my computer and I don't want to activate pybind11.
